### ISSUE TITLE
Questiong

### ISSUE THREAD

**Issue by dcdebug** [tty228/luci-app-wechatpush#229]
Install steps:
`
cd /tmp/
 wget  https://github.com/tty228/luci-app-wechatpush/releases/download/v2.09.2/luci-app-serverchan_2.09.2_all.ipk
opkg update 

opkg install luci-app-serverchan_2.09.2_all.ipk
`
But ,Then I can't found the serverchan on the admin backend.

**Comment by tty228** [comment]
Try the following commands to refresh the cache:
rm -rf /tmp/luci-*
/etc/init.d/uhttpd restart
/etc/init.d/rpcd restart

However, I suggest you install version 3.0 because I didn't add multi-language support before that version.
I didn't expect foreign users to use this plugin. The content it pushes and the log output are all in Chinese, so it may not be very suitable for use.

https://github.com/tty228/luci-app-wechatpush/releases/tag/v3.0.0

**Comment by xibaolai** [comment]
请教大佬，最新的源码怎么并入lede源码进行编译？最新的源码并入编译后，没有设置页面了。

**Comment by tty228** [comment]
> 请教大佬，最新的源码怎么并入lede源码进行编译？最新的源码并入编译后，没有设置页面了。

git clone -b openwrt-18.06 https://github.com/tty228/luci-app-wechatpush.git

**Comment by xibaolai** [comment]
谢谢大佬！
